- name: updated yum
  yum:
    name: "*"
    state: latest
  become: yes

    
- name: deployed .bash_profile
  template:
    src: .bash_profile
    dest: ~/.bash_profile
    mode: 0644
  become_user: "{{ __working_user }}"

- name: made dir .bash.d
  file:
    path: ~/.bash.d
    state: directory
    mode: 0755
  become_user: "{{ __working_user }}"

- name: set LANG={{ __locale }} in /etc/locale.conf
  lineinfile:
    dest: /etc/locale.conf
    regexp: "^LANG="
    line: "LANG={{ __locale }}"
    backup: yes
  become: yes


- name: created backup sshd_config
  copy:
    src: /etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config.org
  become: yes

- name: Prevented ssh time out
  blockinfile:
    dest: /etc/ssh/sshd_config
    insertafter: '^#ClientAliveCountMax 3'
    content: |
      ClientAliveInterval 30
      ClientAliveCountMax 3
    validate: sshd -t -f %s
  notify:
    - sshdRestart
  become: yes